//--------------------------------------------------------------
// File     : maze_txtmap.h
// Purpose  : Support loading maps from const uint8_t arrays
//            generated by tools/map_converter.py
//--------------------------------------------------------------

#ifndef __STM32F4_UB_MAZE_TXTMAP_H
#define __STM32F4_UB_MAZE_TXTMAP_H

#include "stm32f4xx.h"
#include "maze.h"

//--------------------------------------------------------------
// Cell encoding in the const map arrays
//--------------------------------------------------------------
#define TXTMAP_CELL_PATH_FOOD    0   // path with normal food (small dot)
#define TXTMAP_CELL_WALL         1   // wall
#define TXTMAP_CELL_PATH_ENERGY  2   // path with energy food (big dot)
#define TXTMAP_CELL_PATH_EMPTY   3   // path with no food (spawn area etc.)

//--------------------------------------------------------------
// Total size of one map data array
//--------------------------------------------------------------
#define MAZE_TXTMAP_SIZE  (ROOM_CNT_X * ROOM_CNT_Y)

//--------------------------------------------------------------
// Number of txt-imported maps available
// Increase this when adding new maps
//--------------------------------------------------------------
#define MAZE_TXTMAP_COUNT  0

#if MAZE_TXTMAP_COUNT > 0
#define MAZE_TXTMAP_ARRAY_SIZE MAZE_TXTMAP_COUNT
#else
#define MAZE_TXTMAP_ARRAY_SIZE 1
#endif

//--------------------------------------------------------------
// Table of all txt-imported maps for indexing
//--------------------------------------------------------------
extern const uint8_t * const maze_txtmap_table[MAZE_TXTMAP_ARRAY_SIZE];

//--------------------------------------------------------------
// Map names for menu display
//--------------------------------------------------------------
extern const char * const maze_txtmap_names[MAZE_TXTMAP_ARRAY_SIZE];

//--------------------------------------------------------------
// Build function: loads a txt-imported map into the Maze structure
// txt_map_index: 0-based index into maze_txtmap_table[]
//--------------------------------------------------------------
void maze_make_rooms_txtmap(uint32_t txt_map_index);

#endif // __STM32F4_UB_MAZE_TXTMAP_H
