import os
from PIL import Image

def convert_png_to_rgb565_c(png_path, c_path):
    if not os.path.exists(png_path):
        print(f"Error: File {png_path} not found.")
        return False
    
    print(f"Opening image {png_path}...")
    img = Image.open(png_path)
    print(f"Original size: {img.size}")
    
    # Resize to 240x320 (width x height)
    print("Resizing to 240x320...")
    img_resized = img.resize((240, 320), Image.Resampling.LANCZOS)
    
    # Convert to RGB if it is not
    if img_resized.mode != 'RGB':
        img_resized = img_resized.convert('RGB')
        
    pixels = img_resized.load()
    
    print(f"Writing C array to {c_path}...")
    with open(c_path, 'w', encoding='utf-8') as f:
        f.write("//--------------------------------------------------------------\n")
        f.write("// Autogenerated background image array (RGB565)\n")
        f.write("//--------------------------------------------------------------\n\n")
        f.write('#include "..\\stm32_ub_graphic2d.h"\n\n')
        f.write("const uint16_t background_menu_table[] = {\n")
        
        count = 0
        line_data = []
        for y in range(320):
            for x in range(240):
                r, g, b = pixels[x, y]
                # Convert to RGB565
                r5 = (r >> 3) & 0x1F
                g6 = (g >> 2) & 0x3F
                b5 = (b >> 3) & 0x1F
                val = (r5 << 11) | (g6 << 5) | b5
                line_data.append(f"0x{val:04X}")
                
                count += 1
                if count % 12 == 0:
                    f.write(",".join(line_data) + ",\n")
                    line_data = []
        
        if line_data:
            f.write(",".join(line_data) + "\n")
            
        f.write("};\n\n")
        f.write("//--------------------------------------------------------------\n")
        f.write("// Image Structure\n")
        f.write("//--------------------------------------------------------------\n")
        f.write("UB_Image background_menu = {\n")
        f.write("  background_menu_table, // Image Data\n")
        f.write("  240,                   // Width\n")
        f.write("  320,                   // Height\n")
        f.write("};\n")
        
    print("Conversion completed successfully!")
    return True

if __name__ == "__main__":
    convert_png_to_rgb565_c("background_menu.png", "ub_lib/bilder/background_menu.c")
